services:
  strmcreator:
    image: soderlund91/strm-creator:latest
    container_name: strmcreator
    restart: unless-stopped
    ports:
      - "8585:8000"
    volumes:
      - ./config:/config
      - ./data:/data
      - ./media:/media  # Change to where you want your media (left side of the : )
    environment:
      - TZ=UTC

